import HomeSloganSvg from '@/assets/svg/home-title-en.svg'

function slotLang(str: string) {
  return function (slots: any[]): string {
    let res = str
    slots.forEach(slot => {
      res = res.replace(/\{(\w+)\}/i, slot)
    })
    return res
  }
}

const langEN = {
  Nav_Wallet_Connect: 'Sign In',
  Nav_Wallet_Disconnect: 'Sign Out',
  Nav_Badge_Page: 'Badge',
  Nav_Event_Page: 'Event',

  Wallet_Title_MetaMask: 'Meta Mask',
  Wallet_Intro_MetaMask: 'Connect to your MetaMask Wallet Or injected explorer wallet',

  Wallet_Title_WalletConnect: 'WalletConnect',
  Wallet_Intro_WalletConnect: 'Connect to your WalletConnect Wallet',

  Wallet_Intro: 'Connect to explorer wallet',

  UserAction_MyProfile: 'My profile',
  UserAction_Bind_Email: 'Bind Email',
  UserAction_Disconnect: 'Sign Out',

  Bind_Email_Title: 'Bind Email',
  Bind_Email_Des: 'Please enter your email address so that you can log in and receive important notifications via email.',
  Bind_Email_Skip: 'Skip',

  Regist_Title: 'Set a unique Social Layer domain identity',
  Domain_Rule: 'Domains can contain the English-language letters a-z, and the digits 0-9. Hyphens can also be used but it can not be used at the beginning and at the end of a domain name. It should be longer than 6 characters.',
  Regist_Input_Placeholder: 'Your domain',
  Regist_Input_Validate: slotLang('Cannot exceed {n} characters'),
  Regist_Input_Validate_2: slotLang('Cannot less then {n} characters'),
  Regist_Input_Validate_3: 'domain contains invalid characters',
  Regist_Input_Validate_4: slotLang('domain contains invalid character: {n}'),
  Regist_Input_Error_Start: 'domain cannot start with "-"',
  Regist_Input_Error_End: 'domain cannot end with "-"',
  Regist_Input_Empty: 'This item cannot be empty',
  Regist_Confirm: 'Confirm',
  Regist_Dialog_Title: 'Your profile will be created with domain: ',
  Regist_Dialog_ModifyIt: 'Edit',
  Regist_Dialog_Create: 'Create',
  Regist_InUse: 'This domain name is already in use',

  Profile_User_NotExist: 'The user does not exist',
  Profile_User_MindBadge: 'Send a badge',
  Profile_User_IssueBadge: 'Send a badge to ',
  Profile_User_Qrcode_download: 'Download',
  Profile_Tab_Received: 'Badge',
  Profile_Tab_Basic: 'Basic',
  Profile_Tab_NFTPASS: 'NFT Pass',
  Profile_Tab_Minted: 'Created',
  Profile_Tab_Point: 'Point',
  Profile_Tab_Groups: 'Groups',
  Profile_Tab_Lens: 'Lens',
  Profile_Tab_Presend: 'Sending',
  Profile_Show_Wallet: 'Your address is',
  Profile_Show_Email: 'Your email is',
  Profile_Show_Close: 'Close',
  Profile_Show_Copy: 'Copy',
  Profile_Tab_Asset: 'Asset',
  Profile_Tab_Token: 'Token',

  Profile_Asset_Amount: 'Amount',

  Avatar_Upload_Button: 'Upload',

  BadgeDialog_Btn_Login: 'Login to receive',
  BadgeDialog_Btn_Reject: 'Reject',
  BadgeDialog_Btn_Accept: 'Accept',
  BadgeDialog_Btn_Face2face: 'QR code',
  BadgeDialog_Btn_share: 'Send',
  BadgeDialog_Btn_Issue: 'Send again',
  BadgeDialog_Btn_None_Left: 'What a pity',

  BadgeDialog_Label_Creator: 'Creator',
  BadgeDialog_Label_Token: 'Badge domain',
  BadgeDialog_Label_Issuees: 'Receiver(s)',
  BadgeDialog_Label_Owner: 'Owner',
  BadgeDialog_Label_Sender: 'Sender',
  BadgeDialog_Label_action_hide: 'Set as private',
  BadgeDialog_Label_action_Burn: 'Burn',
  BadgeDialog_Label_action_public: 'Set as public',
  BadgeDialog_Label_action_top: 'Set to Top',
  BadgeDialog_Label_action_Revoke: 'Revoke',
  BadgeDialog_Label_action_untop: 'UnSet to Top',
  BadgeDialog_Label_hide_tip: 'Only visible to yourself',
  BadgeDialog_Label_Creat_Time: 'Create time',
  BadgeDialog_Label_Private: 'Badge Type',
  BadgeDialog_Label_Private_text: 'Private',
  BadgeDialog_Label_gift_text: 'Gift card',

  BadgeletDialog_title: 'Badge Details',
  BadgeletDialog_presend_title: 'Sending Details',
  BadgeletDialog_invite_title: 'Invite Details',
  BadgeletDialog_gift_title: 'Gift card Details',
  BadgeletDialog_Reason: 'Reason',

  MintBadge_Title: 'Send a badge',
  MintBadge_Upload: 'Badge Image',
  MintBadge_UploadTip: slotLang('Support JPG, GIF, PNG. Max size of {size}'),
  MintBadge_Name_Label: 'Badge Name',
  MintBadge_Name_Placeholder: 'Naming your badge',
  MintBadge_Domain_Label: 'Badge Domain',
  MintBadge_Domain_Placeholder: 'Domain',
  MintBadge_Submit: 'Send to friend',
  MintBadge_Next: 'Next',
  MintBadge_Submit_To: slotLang('Send to {1}'),
  MintBadge_Submiting: 'Sending',
  MintBadge_Domain_Rule: 'The domain is the unique identifier for your badge. <br /> Domains can contain the English-language letters a-z, and the digits 0-9. Hyphens can also be used but it can not be used at the beginning and at the end of a domain name. It should be longer than 4 characters.',

  MintFinish_Title: 'Finish Sending!',
  MintFinish_Button_Later: 'Send later',
  MintFinish_Button_Issue: 'Go to Send',

  IssueBadge_Title: 'Send a badge',
  IssueBadge_Domain: 'Badge Domain',
  IssueBadge_Reason: 'Reason (Optional)',
  IssueBadge_Create_time: 'Created',
  IssueBadge_ReasonPlaceholder: 'Reason for issuing',
  IssueBadge_Issuees: 'receiver(s)',
  IssueBadge_Support: 'Support <br />1.wallet address; <br/>2. domain end with \'.dot/.eth\'; <br /> 3.Social Layer username or user domain',
  IssueBadge_IssueesPlaceholder: 'Enter receiver\'s domain or wallet address',
  IssueBadge_GoToIssue: 'Go to Send',
  IssueBadge_Issuesing: 'Sending',
  IssueBadge_Mint: 'Send',
  IssueBadge_Mint_later: 'Send later',
  IssueBadge_Sendwithlink: 'By link',
  IssueBadge_By_QRcode: 'By QR Code',
  IssueBadge_Sendwithdomain: 'By name',
  IssueBadge_linkbtn: 'Link',
  IssueBadge_Eventbtn: 'Event',
  IssueBadge_Address_List_Title: 'Select receivers',
  IssueBadge_Input_Error: 'Invalid domain, wallet address or username.',
  IssueBadge_Input_Des: 'Input the domain/wallet/email address of the badge that receiver can receive the badge.',

  IssueFinish_Title: 'Share',
  IssueFinish_Share_By_Qrcode: 'Share by QRcode',
  IssueFinish_Share_By_Link: 'Share by Link',
  IssueFinish_CopyLink: 'Copy link',
  IssueFinish_Screenshot: 'Please take a screenshot for sharing',
  IssueFinish_Screenshot_Or: 'or',
  IssueFinish_share: '#1 has sent you an NFT badge: #2. Go and get it! \n It is recommended to use metamask or imToken browser to access the website.\n #3',
  IssueFinish_Share_Card_text_1: 'sent you a badge',
  IssueFinish_Share_Card_text_2: 'Send by @Social Layer',

  Search_Cancel: 'Cancel',
  Search_Label_Domain: slotLang('Domain for "{keyword}":'),
  Search_Label_Badge: slotLang('Badges for "{keyword}":'),

  Home_SubTitle: 'The social honor of your life your life',
  Home_Content: 'Each POAP is a gift from an issuer to collectors, in celebration of a special shared memory.<br>By minting these memories to the blockchain, collectors build a rich tapestry of tokenized experiences which unlock a world of possibilities.',
  Home_SearchPlaceholder: 'Search for Wallet/Domain',
  Home_ButtonLabel: 'Explore my collection',
  Home_ButtonTip: 'Connect Wallet',

  Copied: 'Copied',

  Landing_Title: 'Welcome to <span>Social Layer 🎉</span>',
  Landing_Sub_Tittle_1: 'What is Social Layer ?',
  Landing_Sub_Tittle_2: 'What can you do?',
  Landing_Sub_Tittle_3: 'How to send a badge?',
  Landing_Des_1: 'A dApp where anyone can send badges to anyone, building a person\'s digital identity based on subjective, unquantifiable value. Badge issuance is not subject to third-party review or approval, and the most valuable badges will naturally spring up in the multivalued community.',
  Landing_Des_2: 'Express your feelings towards others by awarding badges, and discover more like-minded people through badges.',
  Landing_Des_3: 'Click \'Get Start\' to create your own on-chain identity. Go to the profile page and award badges.  As early users, Social Layer will pay gas fees for you.',
  Landing_Des_4: 'For more information: ',
  Landing_White_Paper: 'Social Layer whitepaper',
  Landing_Button: 'Get Start',
  Landing_Badge_Receive: 'Login to receive',

  WhatsApp_Share: slotLang('{domain} send you an NFT badge: {badge}. Go get it! {url}'),

  Login_Title: 'Login with Email',
  Login_alert: 'Please enter a email address',
  Login_continue: 'Continue',
  Login_Placeholder: 'Your Email',
  Login_option: 'Or more option',
  Login_input_Code_title: 'Check your inbox',
  Login_input_Code_des: slotLang('Enter the code we sent to {email} to complete your account set-up.'),

  Page_Back: 'Back',
  Page_Back_Done: 'Done',

  Picture_Recommend_Title: 'Example',
  Picture_Recommend_Create_By_Canva: 'Create by Canva',
  Picture_Recommend_Download_A_Template: 'Download a template',

  Quantity_input_label: 'Quantity',
  Quantity_Unlimited: 'Unlimited',

  Presend_step: 'Fill in the quantity of badges. <br /> The badges will be sent to the receivers as a link.',

  presend_share_link: '#1 has sent you an NFT badge: #2. Go and get it! \n #3 \n It is recommended to use metamask or imToken browser to access the website.',

  Activity_Page_type: 'Activity',
  Activity_State_Registered: 'Registered',
  Activity_State_Created: 'Created',
  Activity_Online_Event: 'Online Event',
  Activity_Max_Participations: 'Up to #1 participations',
  Activity_login_title: 'No Registered Events Yet!',
  Activity_login_des: 'Log in to participate in a fun event',
  Activity_login_btn: 'Log in / Sign in',
  Activity_search_placeholder: 'Search events…',
  Activity_no_activity: 'No activity yet～',
  Activity_latest: 'Latest Event',
  Activity_Greeting_Morning: 'Good Morning',
  Activity_Greeting_Afternoon: 'Good Afternoon',
  Activity_Greeting_Evening: 'Good Evening',
  Activity_My_Register: 'My register',
  Activity_All_Activity: 'All Event',
  Activity_Btn_Create: 'Create Event',
  Activity_Btn_Modify: 'Modify Event',
  Activity_Create_title: 'Create a Event',
  Activity_Setting_title: 'Event Setting',
  Activity_Create_Done: 'Done',
  Activity_Create_Success: 'Create Successfully 🎉',
  Activity_Create_Success_Scan_tips: 'Scan the code <br> and attend the event',
  Activity_Create_Success_Scan_tips_2: '| Activity',
  Activity_Scan_checkin: 'Scan QR code to Check in',
  Activity_Registered_participants: 'Registered participants',
  Activity_originators: 'Host',
  Activity_Des: 'Activity content',
  Activity_Participants: 'Participants',
  Activity_Cancel_registration: 'Cancel Registration',
  Activity_Form_Cover: 'Cover/Poster',
  Activity_Form_Name: 'Event Name',
  Activity_Form_Details: 'Details',
  Activity_Form_Starttime: 'When will it happen?',
  Activity_Form_Where: 'Where is the event taking place?',
  Activity_Form_participants: 'What is the maximum number of participants?',
  Activity_Form_Duration: 'Set Duration',
  Activity_Form_Hoster: 'Host',
  Activity_Form_Label: 'Label',
  Activity_Detail_Btn_Modify: 'Modify',
  Activity_Detail_Btn_Cancel: 'Cancel Event',
  Activity_Detail_Btn_Checkin: 'Check-in',
  Activity_Detail_Btn_Attend: 'Attend-in',
  Activity_Detail_Btn_Joined: 'Joined',
  Activity_Detail_Btn_End: 'Event has ended',
  Activity_Detail_Btn_AttendOnline: 'Attend online',
  Activity_quantity_Input: 'custom',

  New_Year_1: 'Cast your New Year wishes into a digital badge.',
  New_Year_2: 'Reason for issuing :',
  New_Year_3: 'Send you a badge, scan <br> the code to get',
  Save_Card: 'Save to album',

  Group_invite_title: 'Invite',
  Group_invite_badge_name: slotLang('Member of {groupName}'),
  Group_invite_message: 'Invitation Message',
  Group_invite_receiver: 'Receiver(s)',
  Group_invite_Nondesignated: 'Non-designated',
  Group_invite_Designated: 'Designated',
  Group_invite_default_reason: slotLang('Invite you to become a member of {n}'),
  Group_invite_detail_benefits: 'Benefits',
  Group_invite_detail_benefits_des: slotLang('You will automatically become a member of {n} organization.'),
  Group_invite_share: '#1 has sent you an NFT badge: #2. Go and get it! \n #3 \n It is recommended to use metamask or imToken browser to access the website.',

  Group_regist_confirm: 'Create a group',
  Group_regist_owner: 'Group owner',
  Group_regist_confirm_dialog: 'This group will be created with domain: ',
  Group_regist_des: 'Badges are send to members\nin the name of the organization',
  Group_regist_title: 'Set a unique Social Layer domain for your group!',

  Group_setting_title: 'Settings',
  Group_setting_dissolve: 'Freeze the Group',
  Group_freeze_dialog_title: 'Are you sure you to freeze this group？',
  Group_freeze_dialog_des: 'Once frozen, all information in this group will no longer be displayed and cannot be recovered. Badge award records can still be retrieved.',
  Group_freeze_Dialog_confirm: 'Freeze',
  Group_freeze_Dialog_cancel: 'Cancel',

  Group_relation_ship_member: 'Member',
  Group_relation_ship_owner: 'Owner',

  Follow_detail_followed: 'Followers',
  Follow_detail_following: 'Following',
  Follow_detail_Recently: 'Recently',
  Follow_detail_groups: 'Groups',
  Follow_detail_btn_mint: 'Send A badge For Your Group',

  Group_detail_tabs_member: 'Members',
  Group_detail_tabs_Vote: 'Votes',
  Group_detail_tabs_Group: 'Board',
  Group_detail_tabs_Event: 'Events',
  Group_detail_tabs_Invite: 'Invited',
  Group_detail_Join_Time: 'Joined',

  Relation_Ship_Action_Follow: 'Follow',
  Relation_Ship_Action_Followed: 'Followed',
  Relation_Ship_Action_Following: 'Following',
  Relation_Ship_Action_Join: 'Join',
  Relation_Ship_Action_Joined: 'Joined',
  Relation_Ship_Action_Leave: 'Leave group',
  Relation_Ship_Action_Unfollow: 'Unfollow ',

  Empty_Text: 'No Data yet~',
  Empty_No_Badge: 'No badge yet~',
  Empty_No_Present: 'No Sending yet~',
  Empty_No_Group: 'No group yet~',
  Empty_No_Invite: 'No invite yet~',

  Search_Tab_Domain: 'Domain',
  Search_Tab_Badge: 'Badge',
  Search_Tab_Event: 'Event',

  Badgebook_Dialog_Choose_Badgebook: 'Choose from Badge book',
  Badgebook_Dialog_Choose_Badge: 'Choose from Created',
  Badgebook_Dialog_Choose_Draft: 'Choose from Draft',
  Badgebook_Dialog_Cetate_Badge: 'Create a new badge',
  Badgebook_Dialog_Recognition_Badge: 'Basic Badge',
  Badgebook_Dialog_Recognition_Des: 'Basic badge, evaluation of others',
  Badgebook_Dialog_Points: 'Points',
  Badgebook_Dialog_Points_Des: 'Create points systems in groups',
  Badgebook_Dialog_Privacy: 'Privacy Badge',
  Badgebook_Dialog_Privacy_Des: 'Only receivers can see the badge',
  Badgebook_Dialog_NFT_Pass: 'NFT Pass',
  Badgebook_Dialog_NFT_Pass_Des: 'Given by the groups to the person',
  Badgebook_Dialog_Gift: 'Gift Card',
  Badgebook_Dialog_Gift_Des: 'Send badge with benefits',

  Dialog_Public_Image_Title: 'Choose a image for badge',
  Dialog_Public_Image_UploadBtn: 'Upload a image',
  Dialog_Public_Image_UploadBtn_Des: 'JPG or PNG. Max size of 800K',
  Dialog_Public_Image_List_Title: 'Public',

  Cropper_Dialog_Title: 'Edit image',
  Cropper_Dialog_Btn: 'Apply',

  Presend_Qrcode_Badge: 'badge',
  Presend_Qrcode_isGroup: 'Group ',
  Presend_Qrcode_Des: slotLang('{1} sent you a {2}.'),
  Presend_Qrcode_Recommended : 'Recommended',
  Presend_Qrcode_Scan: 'Scan the QR Code',
  Presend_Qrcode_Limit: slotLang('Limited to {1} person'),
  Presend_Qrcode_Time: slotLang('Expiry time : {1}'),
  Presend_Qrcode_Time_2: slotLang('Starts time : {1}'),
  Presend_Qrcode_Expired: 'The badge is no longer valid',
  Presend_Qrcode_Regen: 'Regenerate the QR code',

  Home_Page_New_Title: 'Create a badge',
  Home_Page_New_Des: 'Join now to start creating badges, describing your achievements, and awarding them to deserving individuals.',
  Home_Page_New_Btn: 'Create your badge',

  Badgelet_List_Title: 'Collected',
  Badgelet_List_Unit: 'Badges',
  Created_List_Title: 'Created',

  Dialog_Copy_Btn: 'Ok',
  Dialog_Copy_Title: 'Copied successfully！',
  Dialog_Copy_Message: 'Share and open the link in a browser.',

  Profile_Bio_More: 'More…',
  Profile_Bio_Less: 'Less',

  Profile_Edit_Title: 'Edit Profile',
  Profile_Edit_Avatar: 'Avatar',
  Profile_Edit_Ncikname: 'Nick name',
  Profile_Edit_Bio: 'Bio',
  Profile_Edit_Bio_Placeholder: 'Set a bio',
  Profile_Edit_Location: 'Location',
  Profile_Edit_Social_Media: 'Social media',
  Profile_Edit_Social_Media_Edit: 'Edit',
  Profile_Edit_Social_Media_Edit_Dialog_Title: 'Your ',
  Profile_Edit_Social_Confirm: 'Confirm',
  Profile_Edit_Save: 'Save',
  Profile_Edit_Leave: 'Leave',
  Profile_Edit_Cancel: 'Cancel',
  Profile_Edit_Leave_Dialog_Title: 'Are you sure to leave?',
  Profile_Edit_Leave_Dialog_Des: 'You haven\'t saved your settings yet.',

  Group_Member_Manage_Dialog_Title: 'Member Management',
  Group_Member_Manage_Dialog_Confirm_Btn: 'Remove from the group',
  Group_Member_Manage_Dialog_Confirm_Dialog_des: slotLang('Are you sure to remove {1} from the group？'),
  Group_Member_Manage_Dialog_Confirm_Dialog_Confirm: 'Remove',
  Group_Member_Manage_Dialog_Confirm_Dialog_Cancel: 'Cancel',

  Create_Point_Title: 'Create a point',
  Create_Point_Symbol: 'Symbol',
  Create_Point_Image: 'Image',
  Create_Point_Name: 'Name',
  Create_Point_Name_Placeholder: 'Fill in the name, eg. Knowledge Points',
  Create_Point_Symbol_Placeholder: 'Fill in the symbol, eg. PT',
  Create_Point_Des: 'Description (Optional)',
  Create_Point_Transferable: 'Transferable',
  Create_Point_Transferable_Tips: 'Allows the owner to transfer the badge and its benefits to others.',

  Create_NFT_Title: 'Create a NFT Pass',
  Create_NFT_Image: 'Image',
  Create_NFT_Name: 'Name',
  Create_NFT_Name_Placeholder: 'Fill in the name',
  Create_NFT_Name_Domain: 'Domain',
  Create_NFT_Name_Des: 'Description (Optional)',

  Create_Nft_success: 'Create Successfully',
  Create_Nft_success_des: 'Your NFT Pass have been created',
  Issue_Nft_Title: 'Send NFT Pass',
  Issue_Nft_Start: 'Start date',
  Issue_Nft_End: 'Expiry date',

  NFT_Detail_title: 'Nft Pass Details',
  NFT_Detail_checkin_title: 'Check In Records',
  NFT_Detail_Des: 'Description',
  NFT_Detail_Check: 'Check In',
  NFT_Detail_use: 'Use the NFT Pass',
  NFT_Detail_show_record_btn: 'View Records',
  NFT_Detail_Expiration: 'Expiration Date',
  NFT_Detail_Unavailable: 'Not in the validity period',

  Point_Detail_Title: 'Point Detail',

  Create_Point_success: 'Create Successfully',
  Create_Point_success_des: 'Your Points have been created',
  Issue_Point_Title: 'Send Points',
  Issue_Point_Point: 'Points',

  Dialog_Check_In_Title: 'Check In',

  Create_Privacy_Title: 'Create privacy badge',
  Create_Privacy_Tips: 'Only you and the owner can view the badge, others can only see the creator and owner of the badge.',

  Create_Gift_Title: 'Create a Gift card',
  Create_Gift_Benefits: 'Benefits',

  Selector_issue_type_gift: 'Send the Gift card',
  Selector_issue_type_gift_times: 'Amount of benefits',
  Create_gift_success: 'Create Successfully',
  Create_gift_success_des: 'Your Gift card have been created',

  Gift_detail_check_btn: 'Check',
  Gift_Detail_use: 'Use',
  Gift_Detail_amount: 'Times Remaining',
  Gift_Detail_check_remain: slotLang('Checked! Remaining {1} Times'),

  Gift_Checked_Title: 'Checked Successfully',
  Gift_Checked_Des: 'Your benefits have been used.',
  Gift_Checked_Btn: slotLang('Use again (Remaining {1} times)'),
  Gift_Checked_show_remain: slotLang('Remaining {1} times'),
  Gift_Checked_show_receiver: 'receiver',
  Gift_Checked_show_last_consume: 'last consume: ',

  Create_Badge_Success_Title: 'Create Successfully',
  Create_Badge_Success_Des: 'Your badge have been created',

  Selector_issue_type_badge: 'Send the badge',
  Selector_issue_type_amount: 'Badge amount',


  Dialog_Transfer_Title: 'Transfer to',
  Dialog_Transfer_Confirm: 'Transfer',

  Detail_Transfer_Accept_Title_Gift: 'You received an Gift Card',
  Detail_Transfer_Accept_Title_Nft: 'You received an Nft Pass',
  Detail_Transfer_Accept_Title_Point: 'You received an Nft Point',
  Detail_Transfer_Accept_Confirm: 'Ok',
  Detail_Transfer_Accept_From: 'From',


  Dialog_Revoke_Title: 'Select owners',
  Dialog_Revoke_Confirm_Title: 'Are you sure you to burn the badge?',
  Dialog_Revoke_Des: 'Once revoked, the badge and benefits will be invalid, but the record can be found on the chain.',
  Dialog_Revoke_Confirm: 'Revoke',


  Dialog_burn_Title: 'Are you sure you to burn this badge?',
  Dialog_burn_Confirm_des: 'Once burned, the badge and benefits will be invalid, but the record can be found on the chain.',

  Vote_Create_Page_Title: 'Create vote',
  Vote_Create_Title: 'Vote name',
  Vote_Create_Title_Placeholder: 'Fill in title',
  Vote_Create_Des: 'Description (Optional)',
  Vote_Create_Content_Placeholder: 'Fill in description (Optional)',
  Vote_Create_Option_Input_Title: 'Option',
  Vote_Create_Multiple_Choice: 'Multiple choice',
  Vote_Create_Show_Voter: 'Show voters',
  Vote_Create_Auth: 'Voting authority',
  Vote_Create_Auth_Member: 'All members in this group',
  Vote_Create_Auth_Badge: 'Badge owners',
  Vote_Create_Auth_Badge_count: 'Used number of badges as a weight',
  Vote_Create_Has_Expire: 'Closing time for voting',
  Vote_Create_Has_Start: 'Starting time for voting',
  Vote_Create_Create_Btn: 'Create',
  Vote_Create_Voters: 'Voters',

  Vote_Confirm_Dialog_Title: slotLang('Are you sure vote 「{1}」?'),
  Vote_Confirm_Dialog_Confirm: 'Vote it',
  Vote_Confirm_Dialog_Cancel: 'Later',
  Vote_Confirm_Dialog_Des: 'You can\'t change it after you vote it',
  Vote_Confirm_Dialog_Selected: 'Selected：',

  Vote_Already_Voted: 'You have already voted',
  Vote_Close_Time: 'Voting will close at ',
  Vote_Start_Time: 'Voting will start at ',
  Vote_Close_Once: 'You only can select one option',

  Vote_Eligibility_Member: 'Only members in this group can vote',
  Vote_Eligibility_Badge: slotLang('Group member who have the badge 「{1}」can vote'),

  Vote_detail_edit: 'Edit',
  Vote_detail_Title: 'Vote',
  Vote_detail_Cancel: 'Delete',
  Vote_detail_hoster: 'Voting initiator : ',

  Vote_Delete_Vote_title: 'Are you sure you to delete the vote？',
  Vote_Delete_Vote_Des: 'Voting data cannot be recovered after deletion.',

}

export type LangConfig = typeof langEN
export default langEN
